AppBundle\Entity\AccessToken:
    type: entity
    table: access_token
    id:
        id:
            id: true
            type: string
            length: 255
    manyToOne:
        customer:
            targetEntity: Customer
            joinColumn:
                name: costumer_id
                referencedColumnName: id
        client:
            targetEntity: Client
            joinColumn:
                name: client_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
