AppBundle\Entity\CustomerProfile:
    type: entity
    table: customer_profile
    id:
        id:
            id: true
            type: string
            length: 255
        customer:
            associationKey: true
    fields:
        avatarURL:
            type: string
            length: 255
            nullable: true
        displayName:
            type: string
            length: 255
            nullable: true
        created:
            type: date
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: date
            nullable: true
    oneToOne:
        customer:
            targetEntity: Customer
            joinColumn:
                name: costumer_id
                referencedColumnName: id
            inversedBy: profile
            cascade: ["persist", "merge"]
