AppBundle\Entity\Customer:
    type: entity
    table: customer
    repositoryClass: AppBundle\EntityRepository\CustomerRepository
    id:
        id:
            id: true
            type: string
            length: 255
    lifecycleCallbacks: {  }
