AppBundle\Entity\Customer:
    type: entity
    table: customer
    repositoryClass: AppBundle\EntityRepository\CustomerRepository
    id:
        id:
            id: true
            type: string
            length: 255
    fields:
        created:
            type: date
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: date
            nullable: true
    oneToMany:
        registrationAttempts:
            targetEntity: RegistrationAttempt
            mappedBy: customer
            cascade: ["persist", "merge"]
        accessTokens:
            targetEntity: AccessToken
            mappedBy: customer
            cascade: ["persist", "merge"]
        authCodes:
            targetEntity: AuthCode
            mappedBy: customer
            cascade: ["persist", "merge"]
        refreshTokens:
            targetEntity: RefreshToken
            mappedBy: customer
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
