AppBundle\Entity\EmailMessage:
    type: entity
    table: email_message
    id:
        customer:
            associationKey: true
        message:
            associationKey: true
    fields:
        about:
            type: string
            length: 255
        fromAddress:
            type: string
            length: 255
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        customer:
            targetEntity: Customer
            joinColumn:
                name: costumer
                referencedColumnName: id
            cascade: ["persist", "merge"]
        message:
            targetEntity: Message
            joinColumn:
                name: message
                referencedColumnName: id
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
