AppBundle\Entity\RegistrationAttempt:
    type: entity
    table: registration_attempt
    id:
        id:
            id: true
            type: string
            length: 255
        customer:
            associationKey: true
    fields:
        status:
            type: integer
        token:
            type: string
            length: 255
        smsId:
            type: string
            length: 255
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        customer:
            targetEntity: Customer
            joinColumn:
                name: costumer
                referencedColumnName: id
            inversedBy: registrationAttempts
            cascade: ["persist", "merge"]
    lifecycleCallbacks:
        prePersist: [ convertStatusToInteger ]
        postPersist: [ convertStatusFromInteger ]
        postLoad: [ convertStatusFromInteger ]
        preUpdate: [ convertStatusToInteger ]
        postUpdate: [ convertStatusFromInteger ]
