# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    mum.oauth.storage:
        class: AppBundle\Services\MUMOAuthStorage
        arguments:
            - "@fos_oauth_server.client_manager"
            - "@fos_oauth_server.access_token_manager"
            - "@fos_oauth_server.refresh_token_manager"
            - "@fos_oauth_server.auth_code_manager"
            - "@fos_oauth_server.user_provider"
            - "@security.encoder_factory"
        public: false

    fos_oauth_server.server:
        class: AppBundle\Services\MUMOAuthServer
        arguments:
            - "@mum.oauth.storage"
            - "%fos_oauth_server.server.options%"

    mum.rest.security.authentication.provider:
        class: AppBundle\Security\Authentication\Provider\RestProvider
        arguments:
          - ""
        public: false

    mum.rest.security.authentication.listener:
        class: AppBundle\Security\Firewall\RestListener
        arguments:
          - "@security.token_storage"
          - "@security.authentication.manager"
        public: false

    mum.twilio:
        class: AppBundle\Services\Twilio
        arguments:
          - "@twilio.api"
          - "%twilio_send_number%"

    mum.customer.registration:
        class: AppBundle\Services\CustomerRegistration
        arguments:
          - "@mum.twilio"
          - "@doctrine.orm.entity_manager"

    mum.customer.profile:
        class: AppBundle\Services\CustomerProfile
        arguments:
          - "%customer_avatar_base_path%"
          - "%customer_avatar_base_url%"
          - "@doctrine.orm.entity_manager"

    mum.message.dispatcher:
        class: AppBundle\Services\MessageDispatcher
        arguments:
          - ["Email", "SMS", "Instant"]
          - "@service_container"

    mum.message.handler.email:
        class: AppBundle\Services\EmailMessageHandler
        arguments:
          - "@mailer"
          - "@doctrine.orm.entity_manager"

    mum.message.handler.sms:
        class: AppBundle\Services\SMSMessageHandler
        arguments:
          - "1"
          - "@doctrine.orm.entity_manager"

    mum.message.handler.instant:
        class: AppBundle\Services\InstantMessageHandler
        arguments:
          - "1"
          - "@doctrine.orm.entity_manager"