<?php

namespace AppBundle\EntityRepository;

use Doctrine\ORM\EntityRepository;
use Scheduler\Scheduler\ScheduledMessageStatusCreated;

/**
 * ScheduledMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduledMessageRepository extends EntityRepository
{
    /**
     * Get Scheduled Messages available by Message Type
     *
     * @param string $from
     * @param string $where
     * @return array
     */
    public function findDeliveryReady($from, $where)
    {
        $query = 'SELECT schedule, message, receiver, messageDependant
                 FROM AppBundle:ScheduledMessage schedule,
                 AppBundle:Message message,
                 AppBundle:MessageReceiver receiver,';
        $query .= $from;
        $query .= ' WHERE schedule.status = :status
                 AND schedule.at <= :scheduledDate
                 AND schedule.message = message.id
                 AND schedule.message = receiver.message';
        $query .= $where;
        $query .= ' ORDER BY schedule.at ASC';
        return $this->getEntityManager()
            ->createQuery($query)
            ->setParameters([
                'status' => (new ScheduledMessageStatusCreated())->getId(),
                'scheduledDate' => new \DateTime()
            ])
            ->getResult();
    }
}